### ISSUE TITLE
Loading Circle for TutorRegistration & TutorSearchRequest

### ISSUE THREAD

**Issue by Phong6698** [MastersProjects/staySmart#30]
Loading Circle after submit

**Comment by zperee** [comment]
Added on TutorSearchRequestComponent and TutorRegistrationComponent. Where else should we add this?

Can be added with `this.spinner.show();` and `this.spinner.hide();`

See reference: https://www.npmjs.com/package/ngx-spinner

**Comment by Phong6698** [comment]
> Added on TutorSearchRequestComponent and TutorRegistrationComponent. Where else should we add this?
> 
> Can be added with `this.spinner.show();` and `this.spinner.hide();`
> 
> See reference: https://www.npmjs.com/package/ngx-spinner

I guess for now nowhere. @zperee you can close it.
