### ISSUE TITLE
E-Mail Template

### ISSUE THREAD

**Issue by Phong6698** [MastersProjects/staySmart#39]
E-Mail HTML Template

- [x] E-Mail an den Anbieter wenn er verifiziert wurde.

- [x] E-Mail für der die Anfrage gemacht hat. (mit link zur seite zb. https://staysmart-dev.web.app/anfragen/af49f4b3-0f21-49ad-ae89-d2bc7fb16176)

- [x] E-Mail für den Anbieter wenn eine Anfrage den Anbieter matched.

- [x] E-Mail an der die Anfrage gemacht hat wenn ein Anbieter eine Offerte gemacht hat.

- [x] E-Mail an den Anbieter mit Kontakt Daten wenn seine Offerte angenommen wurde.

**Comment by jeffreysantanach** [comment]
here are the  requested files :) 
[E-Mails.zip](https://github.com/MastersProjects/staySmart/files/5064601/E-Mails.zip)
