### ISSUE TITLE
Research CMS

### ISSUE THREAD

**Issue by zperee** [MastersProjects/staySmart#7]
Research on how to managed the content on the information sides. 
(Team, Statuten, Verein, Presse, etc.)

**Comment by zperee** [comment]
Use **Contenful** to create a CMS. 
Check out this video: https://www.youtube.com/watch?v=2agJoqviGY4

**Comment by Phong6698** [comment]
> Use **Contenful** to create a CMS.
> Check out this video: https://www.youtube.com/watch?v=2agJoqviGY4

Pricing is 39$/Month
10 free users but only 1 role
https://www.contentful.com/pricing/

**Comment by zperee** [comment]
So the free version is only for development?

**Comment by Phong6698** [comment]
> So the free version is only for development?

looks like it. just for sample app
